### ISSUE TITLE
quicklisp

### ISSUE THREAD

**Issue by MarkusPfundstein** [russell/cl-git#28]
Hi Russel,

is it possible to get this project on quick lisp? Would simplify installation tremendously .

Greetings
Markus

**Comment by Rudolph-Miller** [comment]
Any update on this issue??

**Comment by russell** [comment]
:( sorry i haven't done anything.  I'll do something now though!

**Comment by Rudolph-Miller** [comment]
Glad to hear that.
Looking forward to it :-)

**Comment by Rudolph-Miller** [comment]
https://github.com/quicklisp/quicklisp-projects/issues/948

**Comment by russell** [comment]
Looks like it's included in the most recent Quicklisp acording to the release notes. I haven't had a chance to test it but will tonight.  http://blog.quicklisp.org/2015/07/july-2015-quicklisp-dist-update-now.html

**Comment by Rudolph-Miller** [comment]
Great!! :)

**Comment by russell** [comment]
OK, i have downloaded and double checked, it looks good.
