### ISSUE TITLE
Hardcoded library path for libgit2

### ISSUE THREAD

**Issue by gitfoxi** [russell/cl-git#34]
Hardcoded:

    (:darwin "libgit2.0.dylib")

On my system, homebrew puts these files:

    /usr/local/lib/libgit2.0.25.0.dylib
    /usr/local/lib/libgit2.dylib
    /usr/local/lib/libgit2.25.dylib

Not sure if it should be hardcoded to something else, like `/usr/local/lib/libgit2.dylib` or use some other mechanism like `pkg-config` to find the library.

**Comment by russell** [comment]
I think using LD_LIBRARY_PATH works to override the path for some Lisps, and there is also `cffi:*foreign-library-directories*
` https://cffi.common-lisp.dev/manual/html_node/_002aforeign_002dlibrary_002ddirectories_002a.html , i can provide a way to expose the path to the library.  Do you know of any other libraries that expose the path?

**Comment by russell** [comment]
I have added more hardcoded paths, specifically to support OSX they are located on the development branch here, https://git.sr.ht/~rsl/cl-git it will be merged at some point this year
