### ISSUE TITLE
How to mutate refs?

### ISSUE THREAD

**Issue by jcguu95** [russell/cl-git#44]
I was wandering in the documentation, but I couldn't find how to mutate refs. More specifically, I'm looking for a way to create branch, switch to branch, delete branch, and merge branches. Is it currently possible with `cl-git`?

**Comment by russell** [comment]
so what is possible is
* creating branches
* switching branches

I don't think i have implemented deleting branches

there is no support for merging.  I did look at the merging API, it's not super complicated, but i don't have time to add it right now.  i still have to back fill tests for some of the other API's that i added recently

**Comment by russell** [comment]
But as for documentation you can look at the test suite if you want more examples, 

there are some fixtures that make references, they are basically branches,

```
(def-fixture reference ()
  (with-test-repository ()
    (let ((test-commit (make-test-revision)))
      (make-object 'reference "refs/heads/oid"
                   *test-repository*
                   :target (getf test-commit :sha)))
    (make-object 'reference "refs/heads/symbolic"
                 *test-repository*
                 :target "refs/heads/oid"
                 :type :symbolic)
    (&body)))
```
making a branch is essentially the same, just that `'branch` is passed instead of the `'reference` and that you only need the branch name, not the `refs/heads/` prefix.  But only recent versions have support for creating branches.  i think it's only in v2.0.0 which isn't in quicklisp

**Comment by russell** [comment]
it looks like passing any reference (object) to the `checkout` method will check it out.  Unfortunately it looks like there are no tests for that are :(

I'll look into getting some documentation and tests added

**Comment by jcguu95** [comment]
Thanks for letting me know. I'm moving recently and may be able to help adding later.

Would you please let me know how to create and switch to branch?

**Comment by russell** [comment]
can you take a look at these examples, https://git.sr.ht/~rsl/balanced-parentheses/tree/master/item/src/vcs/git.lisp#L119-129

and let me know if that helps

**Comment by russell** [comment]
I'm going to disable the issue tracker here, please submit any further questions to the mailing list https://lists.sr.ht/~rsl/cl-git
